### ISSUE TITLE
netcdf headers

### ISSUE THREAD

**Issue by rhijmans** [rwinlib/gdal3#1]
I am using `rwinlib/gdal3` in [terra](https://github.com/rspatial/terra) and I would also like to use the `netcdf` library directly. 

I suppose I could pull in `rwinlib/netcdf` as well, but it seems that all its  components (except szip; and ignoring udunits) are also included in `rwinlib/gdal3`. That would suggest that adding the netcdf header files to `rwinlib/gdal3` (and including `szip`) would be preferable.

Am I right? If so, can you add the headers to winlib/gdal3? Or else could I include the header files myself (is there a place where I can get the headers that you used for building `winlib/gdal3`)?  I also note that GDAL reports `NetCDF has netcdf_mem.h:   no`, whereas this file is included in `rwinlib/netcdf`.

Thank you.

**Comment by jeroen** [comment]
Hi, sorry I had missed this message.

I have included the netcdf headers in the new v3.2.1 build. Does this solve your problem?

**Comment by jeroen** [comment]
The headers are there now. Feel free to open a new issue if this doesn't work.
