### ISSUE TITLE
No PDF support

### ISSUE THREAD

**Issue by mdsumner** [rwinlib/gdal3#2]
No urgency on this, but if possible in future to add support? 

I believe that for the PDF driver/s to work we need one of Poppler, PDFium, or Podofo. 

https://gdal.org/drivers/raster/pdf.html#build-dependencies

I see that none of these is enabled. On Linux this works, but on Windows I see: 

```R
pdf("myfile.pdf")
plot(1)
dev.off()


vapour::vapour_raster_info("myfile.pdf")
Error in sds_info_cpp(x) : cannot open dataset

stars::read_stars("myfile.pdf")
trying to read file: C:\temp\myfile.pdf
Error in CPL_read_gdal(as.character(x), as.character(options), as.character(driver),  : 
  file not found
```

It's not clear to me why the PDF driver reports as available ...

```R
 dplyr::filter(sf::st_drivers(), grepl("PDF", name))
    name      long_name write copy is_raster is_vector   vsi
PDF  PDF Geospatial PDF  TRUE TRUE      TRUE      TRUE FALSE
```

On Linux the above example (works in raster, terra, stars, vapour)

```R
 stars::read_stars("myfile.pdf")
stars_proxy object with 1 attribute in file:
$myfile.pdf
[1] "myfile.pdf"

dimension(s):
     from   to offset delta refsys point values x/y
x       1 1050      0     1     NA    NA   NULL [x]
y       1 1050   1050    -1     NA    NA   NULL [y]
band    1    3     NA    NA     NA    NA   NULL    
```

thank you

**Comment by jeroen** [comment]
Yeah, the pdf rendering stack is pretty heavy. Is this really something that you would use? Do people really store raster data in pdf files ? :/

**Comment by mdsumner** [comment]
Well yes, funnily enough "maps" are data ...

I won't plead for it though, can always jump to Linux, and sounds like gdal will fragment and retreat from format support generally anyway.

**Comment by mdsumner** [comment]
Oh, but concretely - can we explicitly disable the pdf support so it doesn't list as available in the driver list?

Unsure if that's just a bug in gdal ...

**Comment by mdsumner** [comment]
I'll try to find out
