### ISSUE TITLE
Update plans?

### ISSUE THREAD

**Issue by wtimmerman-fitp** [rwinlib/gdal3#4]
Hi there! What is the plan for new gdal updates to be incorporated here? If I understand it right, the sf R package will download the library from here during installation from source. See: https://github.com/r-spatial/sf/blob/6e39d6dca180977c16fc0cbce69b9381ec1d9335/tools/winlibs.R

The current version here is 3.4.1.1, and there are a few driver updates in the recent versions of gdal (e.g., writing with OpenFileGDB and FileGDB drivers) that I would love to make use of in R with the sf package. 

Thanks for the info.

**Comment by jeroen** [comment]
Sorry, this repo is no longer updated. R-core now switched to their own build system, and a version of gdal is included with rtools43. You need to ask Tomas Kalibera for updates.

**Comment by wtimmerman-fitp** [comment]
understood, thanks!
